### ISSUE TITLE
Folder structure for cutom plugin in saleor

### ISSUE THREAD

**Issue by ace-han** [ace-han/social_auth#1]
In the developer doc of `saleor`, says Plugin will be auto picked up and appended to `django`'s  `INSTALLED_APPS`.

https://docs.saleor.io/docs/3.0/developer/extending/plugins#loading-your-plugin

Something about `entry points` in `setuptools`, which would **NOT** pollute the `settings.py` in production

That's new to my knowledge.

Let's figure out a folder structure that could fit development and deployment for our custom plugin in `saleor`.

**Comment by ace-han** [comment]
```shell
# setup.cfg
[metadata]
name = social-auth
version = 0.1.0
author = Ace Han
author_email = ace.jl.han@gmail.com
description = A small example package
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/pypa/sampleproject
project_urls =
    Bug Tracker = https://github.com/pypa/sampleproject/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: MIT License
    Operating System :: OS Independent

[options]
packages = find:
python_requires = >=3.9

[options.packages.find]
exclude = tests

[options.entry_points]
saleor.plugins =
    social_auth = social_auth.plugin:SocialAuthPlugin
```

```python
# setup.py  # most flexisible but discouraged by the time of writing
# https://stackoverflow.com/questions/39484863/whats-the-difference-between-setup-py-and-setup-cfg-in-python-projects#60885212
from setuptools import find_packages, setup


setup(
    name='social_auth',
    version="0.2.0",
    license='MIT',
    long_description="file README.md",
    long_description_content_type='text/markdown',
    author='Ace Han',
    author_email='ace.jl.han@gmail.com',  # SEE NOTE BELOW (*)
    packages=find_packages(exclude=['tests']),
    python_requires=">=3.9",
    zip_safe=True,
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    entry_points={
        'saleor.plugins': 'saleor_auth = saleor_auth.plugin:SocialAuthPlugin',
    }
)
```

```toml
# pyproject.toml
# It's not recommended for saleor plugin development  for the time of writing
[tool.poetry]
name = "saleor_auth"
version = "0.3.0"
description = ""
authors = ["Ace Han <ace.jl.han@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
# requires = [
#     # I need entry_points feature
#     # https://setuptools.readthedocs.io/en/latest/userguide/declarative_config.html#options
#     "setuptools>=51",
#     "wheel"
# ]
# build-backend = "setuptools.build_meta"

[tool.poetry.plugins."saleor.plugins"]
"social_auth" = "social_auth.plugin:SocialAuthPlugin"
```

**Comment by ace-han** [comment]
# wheel vs egg

Wheel is considered as standard for built and binary

https://packaging.python.org/discussions/wheel-vs-egg/

```shell
# below is old-school packaging
python setup.py build
python setup.py install
```

```
# new style. PEP 517/518  with a external pyproject.toml
# https://stackoverflow.com/questions/39484863/whats-the-difference-between-setup-py-and-setup-cfg-in-python-projects#60885212
pip install build
python -m build
```

```toml
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
```

**Comment by ace-han** [comment]
```
# for development and debug to original lines
pip install -e .

# for dist with setuptools
pip install build
python -m build
pip install dist/*.whl
```

**Comment by ace-han** [comment]
# A demo plugin example

https://github.com/saleor/saleor-plugin-avatax-excise

and it's github workflow for test, copy & paste for reference here
```yml
name: Pytest

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - master
      - ci/*

env:
  DATABASE_URL: "postgres://saleor:saleor@postgres:5432/saleor"
  SECRET_KEY: ci-test

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.9

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: saleor
          POSTGRES_USER: saleor
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

      - name: Install system dependencies
        run: apt-get install -y libpq-dev

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements_dev.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Checkout Saleor
        uses: actions/checkout@v2
        with:
          repository: mirumee/saleor

      - name: Checkout plugin
        uses: actions/checkout@v2
        with:
          path: plugin

      - name: Installing Saleor
        run: |
          python -m pip install wheel
          python -m pip install -r requirements_dev.txt
      - name: Install plugin's dependencies
        run: |
          cd plugin
          ls -a
          python setup.py install
      - name: Copy plugin to Saleor
        run: |
          cp -r plugin/excise saleor/plugins/avatax
      - name: Run tests
        run: |
          pytest saleor/plugins/avatax/excise

```
